import Head from 'next/head';
import Image from 'next/image';
import { Navigation } from '../../components/Navigation/Navigation';
import Bg from '../../assets/images/bg.jpg';

export default function Home() {
  return (
    <div className="font-sans">
      <Head>
        <title>manifesto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-[1200px] mx-auto flex flex-col justify-center items-center pt-10 text-3xl">
        <Navigation />
        <Image src={Bg} layout="fill" alt="" className=" -z-40" />

        <div className="mt-[240px] max-w-[1100px] flex justify-center items-center">
          <div className="flex">
            <div className="w-1/4 flex justify-center items-center">IMG LOGO</div>
            <div className="w-3/4">
              <p>
                Hello! We're a multidisciplinary community of musicians, media
                artists and DJs from Kyiv, Ukraine. Khvylia was created in April
                2022 during the war in Ukraine and its main goal is cooperation
                of new freshmen talents with experienced music industry experts,
                working on a new generation of artists and musicians, helping
                each other and supporting our community. Unity is our new
                treasure which we want to cultivate.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
