import Head from 'next/head';
import Image from 'next/image';
import { Navigation } from '../../components/Navigation/Navigation';
import Bg from '../../assets/images/bg.jpg';
import Link from 'next/link';

export default function Home() {
  const artists = [
    { name: 'TUCHA', href: 'tucha' },
    { name: 'KAROON', href: 'karoon' },
    { name: 'BADWOR7H', href: 'badwor7h' },
    { name: 'OI FUSK', href: 'oifusk' },
    { name: 'KISS ALLAH', href: 'kissallah' },
    { name: 'RATMIR BILODID EXPERIENCE', href: 'ratmir' },
  ];

  return (
    <div className="font-sans">
      <Head>
        <title>artists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-[1200px] mx-auto flex flex-col justify-start items-start pt-10 text-3xl">
        <Navigation />
        <Image src={Bg} layout="fill" alt="" className="-z-40" />

        <div className="mt-[157px] max-w-[1100px] flex flex-col text-black z-10 ml-[50px]">
          {artists.map(({ name, href }) => {
            return (
              <Link className="block" key={name} href={`artists/${href}`}>
                <a className="text-[90px] h-[95px] cursor-pointer">{name}</a>
              </Link>
            );
          })}
        </div>
      </main>
    </div>
  );
}
