import Head from 'next/head';
import Image from 'next/image';
import { Navigation } from '../components/Navigation/Navigation';
import Bg from '../assets/images/bg.jpg';

export default function Home() {
  return (
    <div className="font-sans">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center pt-10 text-3xl">
        <Navigation />
        <Image src={Bg} layout="fill" alt="" className=" -z-40" />
      </main>
    </div>
  );
}
