import Head from 'next/head';
import Image from 'next/image';
import { Navigation } from '../../../components/Navigation/Navigation';
import Bg from '../../../assets/images/bg.jpg';
import Artist from '../../../assets/images/ahmet.png';
import Link from 'next/link';

export default function Home() {
  return (
    <div className="font-sans">
      <Head>
        <title>artists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-[1200px] mx-auto flex flex-col justify-start items-start pt-10 text-3xl">
        <Navigation />
        <Image src={Bg} layout="fill" alt="" className="-z-40" />

        <div className="mt-[157px] max-w-[1100px] flex text-black z-10 ml-[50px]">
          <div className="max-w-[820px]">
            <h4 className="text-[90px] h-[105px]">AHMET</h4>
            <div className="min-h-[401px] text-white bg-gray-400 flex items-center justify-center">
              IMG
            </div>
            <div className='underline mt-[20px]'>Live Show / Duration 45 min</div>
            <div className='underline mt-[20px]'>Live Show / Duration 45 min</div>
            <p>
              super cool artist really really cool cool coooloo
              coooloooooooooooooooooooooooooooococococoo
              cococococococcococcocococcoooooooooooooooo
              dodwirowirowirowrowriowriowriworiworiwioioo
              woriworiworiworiworiworiworiwprwproiwprowi
              worworiwriworiworiworiwroiwrksskjfksjfngell
              dlskldksdlksldksldksdowkwoiwoeiworiowriwrpp
              sdksldospdopsdospdopsdospdopsdospdopsdospdo
              sdposdposdpsodpsdospdospdopsodpsdopsodpsdop
              spdospdospdospdksldksljfflsfkslkfpwoepwopopp
              dspospdospdospdospdospdospdospdospdospdospdo
              dpsodpsdospdospdklsljfwiopeoowpeo[weo[pw[ep[o{' '}
            </p>
            <p>soundcloud instagram</p>
          </div>
        </div>
      </main>
    </div>
  );
}
