import Head from 'next/head';
import Image from 'next/image';
import { Navigation } from '../../components/Navigation/Navigation';
import Bg from '../../assets/images/bg.jpg';
import Cover from '../../assets/images/cover.png';

export default function Home() {
  return (
    <div className="font-sans">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-[1200px] mx-auto flex flex-col justify-center items-center pt-10 text-3xl">
        <Navigation />
        <Image src={Bg} layout="fill" alt="" className="-z-40" />

        <div className="mt-[240px] max-w-[1100px] flex justify-between text-white">
          <div className="w-[367px] flex flex-col justify-center items-center">
            <Image src={Cover} alt="#" />
            <p className="mt-[29px]">operation perevtilennya</p>
            <p className="">[KHV01]</p>
          </div>
          <div className="w-[367px] flex flex-col justify-center items-center mx-[94px]">
            <Image src={Cover} alt="#" />
            <p className="mt-[29px]">operation perevtilennya</p>
            <p className="">[KHV02]</p>
          </div>
          <div className="w-[367px] flex flex-col justify-center items-center">
            <Image src={Cover} alt="#" />
            <p className="mt-[29px]">operation perevtilennya</p>
            <p className="">[KHV03]</p>
          </div>
        </div>
      </main>
    </div>
  );
}
